services:
    ziti-ctrl:
        image: openziti/ziti-cli
        container_name: ziti-ctrl
        command: >
            edge quickstart
            --home /home/ziggy/quickstart
            --ctrl-address ziti-controller
            --ctrl-port 1280
            --router-address ziti-router
            --router-port 3022
            --password ziggy123
        volumes:
            - ziti-data:/home/ziggy
        networks:
            testnet:
                aliases:
                    - ziti-controller
                    - ziti-router
        expose:
            - 1280
            - 3022

    ziti-host:
        image: openziti/ziti-host:1.1.3
        container_name: ziti-host
        networks:
            testnet:
        volumes:
            -   ziti-host:/ziti-edge-tunnel
        environment:
            - ZITI_ENROLL_TOKEN=eyJhbGciOiJSUzI1NiIsImtpZCI6ImMzNzBiZjA5NGI5MzlhNDM3OTUwZTUwYjY4NDRmOGEwOWY5OWRkYzgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3ppdGktY29udHJvbGxlcjoxMjgwIiwic3ViIjoiVWlmOU9jNjNDTSIsImF1ZCI6WyIiXSwiZXhwIjoxNzI0ODcwMDE2LCJqdGkiOiI4YWU1NmFlNS01MTFjLTRkYmEtYWMzMi00MjA5MTc2NzJjOTciLCJlbSI6Im90dCIsImN0cmxzIjpudWxsfQ.GT39xHKTylCeGQCBUcwTrTr3wzLaTVMQ1vGTjg-JSKFZ705jL-FEAxVwUpBQ0Gh5KQXhYJzggtDdmYqCSVYa7kAzmmuIXQ5awfRGJUIw5KqqxjFeXxvPs0v9zZ1b-ZL1LWyWL432vTw9qvUhn0G5ROs1xJ_WfOI67jN-kPJjDBr6BfcTqmv-sgXFVzOTbZuapEjGoQvLeZRbEh4fqn23wxQUPrmyGwOgMbNLY3YON_Gi8ljFdaigWmSW_p2Usm3KpgRsZAp2lHswoDotc2G0GlmkUXCZeObie0t5MsenzPY4BvhL4wqbihMuij0Lg7qaHEr6XR180wrFoVg8iGgu7iQg_hIHcnXJDVGJUb3G1k_oe94SnhU24NbYNLNUFWmcXynpspvCEYvFEnHgnOKrCqIWg6ANOj1muC_Vsh_5W3FnDXdb5DtAYRyxdJwFrV_Wdzm4Izyv68qmjmoCHezV-sPhTogV7peGX0aYOwnOI1oSpz69YkkGlQWxR9Lp_vDjjZGagrlj_kiZPs7TxlsMnA0hvKmoD_ChJ1v1VexbAQ7vqY4wX4B91TUMIuTGgyb_wNKHUtMVXm36qP_ZIeysjU7A4SPVSNk7VxUUcPn5Pek7psy0RZykjRQnKrWP0rOcypRyIa1RHdkDRGU-hMcFD1SnhRu-FfQ4jVdr0Q81SWU

    ziti-client:
        image: openziti/ziti-router:1.1.9
        container_name: ziti-client
        expose:
            -   3022
        networks:
            testnet:
                ipv4_address: ${HMISIEMENS_ADDRESS:-172.19.1.2}
        environment:
            ZITI_CTRL_ADVERTISED_ADDRESS: ziti-controller
            ZITI_ENROLL_TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6ImMzNzBiZjA5NGI5MzlhNDM3OTUwZTUwYjY4NDRmOGEwOWY5OWRkYzgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3ppdGktY29udHJvbGxlcjoxMjgwIiwic3ViIjoiaC1qVzI0cGJVRiIsImF1ZCI6WyIiXSwiZXhwIjoxNzI0OTI3NjU1LCJqdGkiOiI3NTcwMGY0ZS04NDJkLTRmMWItOWEzMC1jMGY1OTE2YzJlZjUiLCJlbSI6ImVyb3R0IiwiY3RybHMiOm51bGx9.uCm8DPmFQ0WHl8CsvWCm8FYtTPHInhGQd__3qg-GeLiqPbzRg55vacvKkfSQFoqjpvzea_LICvPZK0RQRn4yKoD4QP2K1gnctm0hubCJmUzAoE6Q5Wgw8YBp9u7roLLGoLrCZ3EIqPPtJ2gqaxPFMerGzTN_RC-jBAed_kZK_Js7qrlXBO6LStQUIgDkg4iAwwDx9b1pQHldfu0RLPjnmcBs0T3Q1x3Fb3xsfIzjnVBDuNpEJdA9TFLqpn7WjUu2DqGmaLF8gvf8jif2Wg9Zma54Ki9RpyBCeeZhG44mS0Z0to127zfUQw4kLAsVUQBiJBRDDIN0c_kQXhKzCETOn--CF58pG6NspZqywf0lb74aQba97sxlyJne3qX72iXHfCt6Y_jnoRBl8KeGB0wuRXrfJPohoj454pv3ntbd_Xi7e9pBU49Hzh6AIbJq5z5l8QnkZkTnwlz7cpBYmxLLmtjsmm83tL1iVvzC2K9KOAWrEDxHZB1baESlVsNiLQtUhg2FWzm9KUaURqdLAIRn1EoPqQ391BmVo5K-jyDeDy4uvBiRhakIyWrjXznGUKAas6g7RXer_aCYNhszXppilSddpMFK27hjuF6Q_jVSAzc1v-loCGBJnfpmAqI3lpst4TphnENnV7sLfC6dky5bDw1IVRMh6QEWuzax6US_5sY
            ZITI_ROUTER_NAME: tproxy
        volumes:
            -   ziti-client:/ziti-router
        dns:
            -   127.0.0.1
            -   1.1.1.1
        user: root
        cap_add:
            -   NET_ADMIN

    attacker:
        image: ubuntu:latest
        networks:
            testnet:
        profiles: ["no-auto-start"] 

volumes:
    ziti-data:
        name: ziti-data
    ziti-host:
        name: ziti-host
    ziti-client:
        name: ziti-client