services:
    ziti-ctrl:
        profiles:
            - ziti
        image: openziti/ziti-cli
        container_name: ziti-ctrl
        networks:
            testnet:
                aliases:
                    - ziti-controller
                    - ziti-router
        command: >
            edge quickstart
            --home /home/ziggy/quickstart
            --ctrl-address ziti-controller
            --ctrl-port 1280
            --router-address ziti-router
            --router-port 3022
            --password ziggy123
        working_dir: /home/ziggy
        environment:
            HOME: /home/ziggy
        volumes:
            - ziti-ctrl:/home/ziggy/quickstart
        expose:
            - 1280
            - 3022
        healthcheck:
            test:
                - CMD
                - ziti
                - agent
                - stats
            interval: 3s
            timeout: 3s
            retries: 5
            start_period: 30s
    wait-for-ziti-ctrl:
        profiles:
            - ziti
        depends_on:
            ziti-ctrl:
                condition: service_healthy
        image: busybox
        command: echo "INFO Ziti is cooking"

    ziti-host:
        profiles:
            - host
        image: openziti/ziti-host
        container_name: ziti-host
        networks:
            testnet:
        volumes:
            - ziti-host:/ziti-edge-tunnel
        environment:
            - ZITI_ENROLL_TOKEN

    ziti-client:
        profiles:
            - client
        image: openziti/ziti-router:1.1.9
        container_name: ziti-client
        expose:
            - 3022
        networks:
            testnet:
                ipv4_address: ${HMI_SIEMENS_ADDRESS:-172.19.1.2}
        environment:
            ZITI_CTRL_ADVERTISED_ADDRESS: ziti-controller
            ZITI_ENROLL_TOKEN:
            ZITI_ROUTER_MODE: tproxy
        volumes:
            - ziti-client:/ziti-router
        dns:
            - 127.0.0.1
            - 1.1.1.1
        user: root
        cap_add:
            - NET_ADMIN
        healthcheck:
            test:
                - CMD
                - ziti
                - agent
                - stats
            interval: 3s
            timeout: 3s
            retries: 5
            start_period: 30s

    # attacker:
        # image: ubuntu:latest
        # networks:
            # testnet:
        # profiles: ["no-auto-start"] 

volumes:
    ziti-ctrl:
    ziti-host:
    ziti-client: