services:
    ziti-ctrl:
        profiles:
            - ziti
        image: openziti/ziti-cli
        container_name: ziti-ctrl
        networks:
            testnet:
                aliases:
                    - ziti-controller
                    - ziti-router
        command: >
            edge quickstart
            --home /home/ziggy/quickstart
            --ctrl-address ziti-controller
            --ctrl-port 1280
            --router-address ziti-router
            --router-port 3022
            --password ziggy123
        working_dir: /home/ziggy
        environment:
            HOME: /home/ziggy
        volumes:
            - ziti-ctrl:/home/ziggy/quickstart
        expose:
            - 1280
            - 3022
        healthcheck:
            test:
                - CMD
                - ziti
                - agent
                - stats
            interval: 3s
            timeout: 3s
            retries: 5
            start_period: 30s
    wait-for-ziti-ctrl:
        profiles:
            - ziti
        depends_on:
            ziti-ctrl:
                condition: service_healthy
        image: busybox
        command: echo "INFO Ziti is cooking"

    ziti-plcsiemens-tunneler:
        profiles:
            - host-siemens
        image: openziti/ziti-host
        container_name: ziti-plcsiemens-tunneler
        networks:
            testnet:
        volumes:
            - ziti-plcsiemens-tunneler:/ziti-edge-tunnel
        environment:
            - ZITI_ENROLL_TOKEN

    ziti-plcbeckhoff-tunneler:
        profiles:
            - host-beckhoff
        image: openziti/ziti-host
        container_name: ziti-plcbeckhoff-tunneler
        networks:
            testnet:
        volumes:
            - ziti-plcbeckhoff-tunneler:/ziti-edge-tunnel
        environment:
            - ZITI_ENROLL_TOKEN

    ziti-plcomron-tunneler:
        profiles:
            - host-omron
        image: openziti/ziti-host
        container_name: ziti-plcomron-tunneler
        networks:
            testnet:
        volumes:
            - ziti-plcomron-tunneler:/ziti-edge-tunnel
        environment:
            - ZITI_ENROLL_TOKEN

    ziti-hmisiemens-router:
        profiles:
            - client-siemens
        image: openziti/ziti-router:1.1.9
        container_name: ziti-hmisiemens-router
        expose:
            - 3022
        networks:
            testnet:
                ipv4_address: ${HMI_SIEMENS_ADDRESS:-172.19.1.2}
        environment:
            ZITI_CTRL_ADVERTISED_ADDRESS: ziti-controller
            ZITI_ENROLL_TOKEN:
            ZITI_ROUTER_MODE: tproxy
        volumes:
            - ziti-hmisiemens-router:/ziti-router
        dns:
            - 127.0.0.1
            - 1.1.1.1
        user: root
        cap_add:
            - NET_ADMIN
        healthcheck:
            test:
                - CMD
                - ziti
                - agent
                - stats
            interval: 3s
            timeout: 3s
            retries: 5
            start_period: 30s

    ziti-hmibeckhoff-router:
        profiles:
            - client-beckhoff
        image: openziti/ziti-router:1.1.9
        container_name: ziti-hmibeckhoff-router
        expose:
            - 3022
        networks:
            testnet:
                ipv4_address: ${HMI_BECKHOFF_ADDRESS:-172.19.2.2}
        environment:
            ZITI_CTRL_ADVERTISED_ADDRESS: ziti-controller
            ZITI_ENROLL_TOKEN:
            ZITI_ROUTER_MODE: tproxy
        volumes:
            - ziti-hmibeckhoff-router:/ziti-router
        dns:
            - 127.0.0.1
            - 1.1.1.1
        user: root
        cap_add:
            - NET_ADMIN
        healthcheck:
            test:
                - CMD
                - ziti
                - agent
                - stats
            interval: 3s
            timeout: 3s
            retries: 5
            start_period: 30s

    ziti-hmiomron-router:
        profiles:
            - client-omron
        image: openziti/ziti-router:1.1.9
        container_name: ziti-hmiomron-router
        expose:
            - 3022
        networks:
            testnet:
                ipv4_address: ${HMI_OMRON_ADDRESS:-172.19.3.2}
        environment:
            ZITI_CTRL_ADVERTISED_ADDRESS: ziti-controller
            ZITI_ENROLL_TOKEN:
            ZITI_ROUTER_MODE: tproxy
        volumes:
            - ziti-hmiomron-router:/ziti-router
        dns:
            - 127.0.0.1
            - 1.1.1.1
        user: root
        cap_add:
            - NET_ADMIN
        healthcheck:
            test:
                - CMD
                - ziti
                - agent
                - stats
            interval: 3s
            timeout: 3s
            retries: 5
            start_period: 30s

    # attacker:
        # image: ubuntu:latest
        # networks:
            # testnet:
        # profiles: ["no-auto-start"] 

volumes:
    ziti-ctrl:
        name: ziti-ctrl
    ziti-plcsiemens-tunneler:
        name: ziti-plcsiemens-tunneler
    ziti-plcbeckhoff-tunneler:
        name: ziti-plcbeckhoff-tunneler
    ziti-plcomron-tunneler:
        name: ziti-plcomron-tunneler
    ziti-hmisiemens-router:
        name: ziti-hmisiemens-router
    ziti-hmibeckhoff-router:
        name: ziti-hmibeckhoff-router
    ziti-hmiomron-router:
        name: ziti-hmiomron-router