services:
  unsafe-omron-attacker:
    build:
      context: ../attackers/OmronAttacker
      dockerfile: Dockerfile
    environment:
      PLCOMRON_ADDRESS: ${PLCOMRON_ADDRESS:-192.168.3.1}
      PLCOMRON_PORT: ${PLCOMRON_PORT:-9600}
    container_name: ${OMRON_ATTACKER_CONTAINER_NAME:-unsafe-omron-attacker}
    networks:
      local-testnet:
    profiles: ["no-auto-start"]
    command: ["python3", "OmronAttacker.py"]