services:
  omron-attacker:
    build:
      context: ../attackers/OmronAttacker
      dockerfile: Dockerfile
    tty: true
    environment:
      PLCOMRON_REAL_ADDRESS: ${PLCOMRON_REAL_ADDRESS:-192.168.3.1}
      PLCOMRON_FAKE_ADDRESS: ${PLCOMRON_FAKE_ADDRESS:-10.31.32.33}
      PLCOMRON_PORT: ${PLCOMRON_PORT:-9600}
    container_name: ${OMRON_ATTACKER_CONTAINER_NAME:-omron-attacker}
    networks:
      testnet:
    profiles: ["no-auto-start"]

  # siemens-attacker:
    # build:
      # context: ../attackers/SiemensAttacker
      # dockerfile: Dockerfile
    # environment:
      # PLCOMRON_REAL_ADDRESS: ${PLCSIEMENS_REAL_ADDRESS:-172.19.1.1}
      # PLCOMRON_FAKE_ADDRESS: ${PLCSIEMENS_FAKE_ADDRESS:-10.11.12.13}
      # PLCOMRON_PORT: ${PLCSIEMENS_PORT:-102}
      # PLCSIEMENS_RACK: ${PLCSIEMENS_RACK:-0}
      # PLCSIEMENS_SLOT: ${PLCSIEMENS_SLOT:-1}
    # container_name: ${SIEMENS_ATTACKER_CONTAINER_NAME:-siemens-attacker}
    # networks:
      # testnet:
    # profiles: ["no-auto-start"]
    # command: ["python3", "SiemensAttacker.py"]
