services:
  omron-attacker:
    build:
      context: ../attackers/OmronAttacker
      dockerfile: Dockerfile
    tty: true
    environment:
      PLCOMRON_REAL_ADDRESS: ${PLCOMRON_REAL_ADDRESS:-192.168.3.1}
      PLCOMRON_FAKE_ADDRESS: ${PLCOMRON_FAKE_ADDRESS:-10.31.32.33}
      PLCOMRON_PORT: ${PLCOMRON_PORT:-9600}
    container_name: ${OMRON_ATTACKER_CONTAINER_NAME:-omron-attacker}
    networks:
      testnet:
    profiles: ["no-auto-start"]

  beckhoff-attacker:
    build:
      context: ../attackers/BeckhoffAttacker
      dockerfile: Dockerfile
    environment:
      PLCBECKHOFF_REAL_ADDRESS: ${PLCBECKHOFF_REAL_ADDRESS:-172.19.2.1}
      PLCBECKHOFF_FAKE_ADDRESS: ${PLCBECKHOFF_FAKE_ADDRESS:-10.21.22.23}
      PLCBECKHOFF_PORT: ${PLCBECKHOFF_PORT:-502}
    container_name: ${BECKHOFF_ATTACKER_CONTAINER_NAME:-beckhoff-attacker}
    networks:
      testnet:
    profiles: ["no-auto-start"]
    command: ["python3", "BeckhoffAttacker.py"]
